lint:
	@echo "Running biome linter"
	pnpm next lint

lint-fix:
	@echo "Running biome linter with auto fix"
	pnpm next lint --fix

server:
	@echo "Starting next js server"
	pnpm next dev

format:
	@echo "Running biome formatter"
	pnpm next format
